name: vietqr_gen
description: A zero-dependency, type-safe Dart package for generating and parsing VietQR payload strings compliant with NAPAS 247 specification.
version: 1.2.0
homepage: https://github.com/duymainek/vietqr_gen

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.21.0

topics:
  - qr
  - payment
  - vietnam
  - napas
  - banking